payload:
  - '+.auth0.com'
  - '+.bing.com'
  - '+.chatgpt.com'
  - '+.codesandbox.io'
  - '+.gofrp.org'
  - '+.jsfiddle.net'
  - '+.live.com'
  - '+.netlify.app'
  - '+.openai.com'
  - '+.tortoisesvn.net'
  - '+.unpkg.com'
