port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: debug
external-controller: "0.0.0.0:9090"
secret: ""
tun:
  enable: true
  stack: system
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true
dns:
  enable: true
  ipv6: false
  listen: "0.0.0.0:53"
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - "https://dns.alidns.com/dns-query"
    - "https://doh.pub/dns-query"
    - "tls://dns.rubyfish.cn:853"
  fallback:
    - "tls://1.0.0.1:853"
    - "tls://8.8.4.4:853"
    - "https://doh.opendns.com/dns-query"
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
proxy-providers:
  XXXX:
    type: http
    url: "https://xxxxxxxx?clash=1"
    interval: 864000
    path: ./sub/XXXX.yaml
    health-check:
      enable: true
      interval: 3600
      url: http://www.gstatic.com/generate_204
proxies:
  -
    name: '自定义代理'
    type: socks5
    server: 127.0.0.1
    port: 31080
    tls: false
    skip-cert-verify: true
    udp: false
proxy-groups:
  - name: PROXY
    type: select
    use:
      - XXXX
    proxies:
      - DIRECT
  - name: CUSTOM
    type: select
    proxies:
      - DIRECT
      - 自定义代理
rule-providers:
  mineBlock:
    type: file
    behavior: domain
    path: ./ruleset/mineBlock.yaml
  mineDirect:
    type: file
    behavior: domain
    path: ./ruleset/mineDirect.yaml
  mineProxy:
    type: file
    behavior: domain
    path: ./ruleset/mineProxy.yaml
  lancidr: # 局域网 IP 及保留 IP 地址列表
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400
  private: # 私有网络专用域名
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400
  applications: # 需要直连的常见软件列表
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
  reject: # 广告域名
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  gfw: # GFW
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400
  tld-not-cn: # 非中国大陆使用的顶级域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
rules:
  - IP-CIDR,10.0.0.0/8,CUSTOM
  - DST-PORT,22,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,mineBlock,REJECT
  - RULE-SET,mineDirect,DIRECT
  - RULE-SET,mineProxy,PROXY
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,applications,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,gfw,PROXY
  - RULE-SET,tld-not-cn,PROXY
  - MATCH,DIRECT
